Check if custom setting is used
IRNAS/irnas-usersettings-lib pull request #54
Opened 2024-03-07 14:58 UTC by KristjanZigart

## Description

This PR includes changes to code documentation and two functions for a specific use-case
if a user needs to know if custom or default settings are in use.

## Areas of interest for the reviewer

Folders:
- user_settings
- tests

## Checklist

- [x] My code follows the [style guidelines] as defined by IRNAS.
- [x] I have performed a self-review of my code.
- [x] My changes generate no new warnings.
- [x] I added/updated source code documentation for all newly added or changed functions.
- [x] I updated the CHANGELOG.
- [x] ~~I updated all customer-facing technical documentation.~~ Only internal changes.

## After-review steps

* Reviewer can merge and delete the branch.

2024-03-07 14:58 UTC, KristjanZigart commented
* **#54** <a href="https://app.graphite.dev/github/pr/IRNAS/irnas-usersettings-lib/54?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @KristjanZigart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-11 10:32 UTC, TjazVracko requested changes
This is a good start.
Remember what we discussed in person - you have added the missing functions, but the API now does not make much sense (not your fault :)).

What you still have to do:

1. Add a test for `user_settings_is_set_with_id/key` that tests the desired behaviour. The desired behaviour is: `This function returns true if a default or custom value for this setting exists.` If the tests fail (which they should), fix the implementation.
2. Rename `user_settings_has_default_with_id/key` to `user_settings_is_default_set_with_id/key` (to match the naming of the other two). 
3.  Add a test for `user_settings_is_default_set_with_id/key` that tests the desired behaviour. The desired behaviour is: `This function returns true if a default is set. It does not care about the custom value` 

This way we will have all 3 possible "checks":
1. Does the setting have a value I can use (is_set)
2. Does the setting have a default value (is_default_set)
3. Does the setting have a non-default value (is_custom_set)

2024-03-11 10:37 UTC, TjazVracko requested changes

2024-03-11 10:37 UTC, TjazVracko commented on tests/user_settings/src/main.c
> +ZTEST(user_settings_suite, test_settings_is_custom_set)
Taking another look at this...
Just delete all other data types and only have a test using Strings - the rest is redundant.

You also do not test all possibilities:
1. No default, no value
2. set default, no value
3. no default, set value
4. set default, set value

Modify the test so it sets up all 4 possibilities and then check the return of `user_settings_is_custom_set_with_id`.

2024-03-11 10:38 UTC, TjazVracko commented on tests/user_settings/src/main.c
> +ZTEST(user_settings_suite, test_settings_is_custom_set)
Taking another look at this...
Just delete all other data types and only have a test using Strings - the rest is redundant.

You also do not test all possibilities:

No default, no value
set default, no value
no default, set value
set default, set value
Modify the test so it sets up all 4 possibilities and then check the return of `user_settings_is_custom_set_with_id`.

2024-06-18 07:39 UTC, closed without merging

2024-06-18 07:40 UTC, TjazVracko commented
Work is stale and not used, closing.